'use client'
import { ScrollTable } from '@/components/ScrollTable'
import { TableSearch } from '@/components/TableSearch'
import { ActionMenu } from '@/components/ActionMenu'
import { TableLoadingState } from '@/components/TableLoadingState'
import { Pagination } from '@/components/Pagination'
import { Toast } from '@/components/Toast'
import { useState, useEffect } from 'react'

export default function MarkEntryCbtPage() {
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const [toast, setToast] = useState<{msg: string, type: string} | null>(null)

  const showToast = (msg: string, type: string = 'success') => {
    setToast({ msg, type })
    setTimeout(() => setToast(null), 3000)
  }

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 1200)
    return () => clearTimeout(timer)
  }, [])

  return (
    <div className="page active">
      <div className="pg-hdr">
        <div>
          <div className="pg-title">Mark Entry — Class Test (CBT)</div>
          <div className="pg-sub">System-generated marks (view-only) · <span className="text-red-500 font-medium">Registrar override only</span></div>
        </div>
        <div className="pg-actions">
          <span className="text-[12.5px] text-slate-500 font-medium">View Only — Contact Registrar for Overrides</span>
        </div>
      </div>

      <div className="card mb-5">
        <div className="p-5 pb-0">
          <div className="bg-[#fffbeb] border border-[#fde68a] rounded-md p-4 flex gap-3 text-[13px] text-[#b45309] items-start mb-4">
            <div className="mt-0.5 text-[#d97706]"><i className="lni lni-lock-alt text-[16px]"></i></div>
            <div className="leading-relaxed">
              CBT marks are auto-generated by the server. <strong className="text-amber-700">Only the Academic Registrar</strong> can override. All overrides are logged with user identity, timestamp, and IP address. Original system mark is preserved separately.
            </div>
          </div>
        </div>
        
        <div className="card-hdr">
          <div className="card-title">
            <span className="ctitle-icon"><i className="lni lni-list"></i></span> Records
          </div>
          <TableSearch
            className="w-64"
            placeholder="Search records..."
            value={search}
            onChange={setSearch}
            results={[]}
          />
        </div>
        <ScrollTable>
          <table>
            <thead>
              <tr>
                <th style={{ width: 48 }}></th>
                <th>REG. NO.</th>
                <th>STUDENT</th>
                <th>SYSTEM MARK<br/>(/50)</th>
                <th>OVERRIDE<br/>MARK</th>
                <th>OVERRIDE BY</th>
                <th>OVERRIDE REASON</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <TableLoadingState colSpan={7} />
              ) : (
                <>
              <tr>
                <td>
                  <ActionMenu>
                    <button className="btn btn-neu btn-sm"><i className="lni lni-eye"></i> View Details</button>
                  </ActionMenu>
                </td>
                <td className="font-mono text-slate-500 text-[12.5px]">BCS/2024/0031</td>
                <td className="text-slate-800">Amara Nkosi</td>
                <td className="font-bold text-slate-900">38 / 50</td>
                <td className="text-slate-400">—</td>
                <td className="text-slate-400">—</td>
                <td className="text-slate-400">—</td>
              </tr>
              <tr>
                <td>
                  <ActionMenu>
                    <button className="btn btn-neu btn-sm"><i className="lni lni-eye"></i> View Log</button>
                  </ActionMenu>
                </td>
                <td className="font-mono text-slate-500 text-[12.5px]">BCS/2024/0017</td>
                <td className="text-slate-800">Emmanuel Okello</td>
                <td className="font-bold text-slate-900">46 / 50</td>
                <td className="font-bold text-purple-700">44 / 50</td>
                <td className="text-slate-600 text-[12px]">Registrar - 08<br/>Nov</td>
                <td className="text-slate-600 text-[12px] max-w-[150px]">System error during<br/>submission</td>
              </tr>
              <tr>
                <td>
                  <ActionMenu>
                    <button className="btn btn-neu btn-sm text-purple-700" onClick={() => showToast('Override prompt opened')}><i className="lni lni-pencil"></i> Override</button>
                  </ActionMenu>
                </td>
                <td className="font-mono text-slate-500 text-[12.5px]">BCS/2024/0058</td>
                <td className="text-slate-800">David<br/>Ssemwogerere</td>
                <td className="font-bold text-slate-900">44 / 50</td>
                <td className="text-slate-400">—</td>
                <td className="text-slate-400">—</td>
                <td className="text-slate-400">—</td>
              </tr>
              <tr>
                <td>
                  <ActionMenu>
                    <button className="btn btn-neu btn-sm opacity-50 cursor-not-allowed"><i className="lni lni-ban"></i> Action Blocked</button>
                  </ActionMenu>
                </td>
                <td className="font-mono text-slate-500 text-[12.5px]">BCS/2024/0044</td>
                <td className="text-slate-800">Grace Akello</td>
                <td><span className="bg-red-50 text-red-500 font-medium px-2 py-1 rounded">Blocked — Fee</span></td>
                <td className="text-slate-400">—</td>
                <td className="text-slate-400">—</td>
                <td className="text-slate-400">—</td>
              </tr>
                </>
              )}
            </tbody>
          </table>
        </ScrollTable>
        <div className="p-4 border-t border-slate-100">
          <Pagination page={page} totalPages={6} totalCount={62} onPageChange={setPage} />
        </div>
      </div>
      <Toast toast={toast} />
    </div>
  )
}
